# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on:
  push:
    branches: '*'
  pull_request:
    branches: [ master ]

env:
  PIP_DISABLE_PIP_VERSION_CHECK: 1
  CACHE_EPOCH: 0


defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Upgrade packaging deps
        run: |
          set -eux
          python -m pip install --upgrade --user pip wheel setuptools

      - name: Build distributions
        run: |
          set -eux
          python setup.py sdist bdist_wheel
          cd dist
          sha256sum * | tee SHA256SUMS

      - name: publish dists
        uses: actions/upload-artifact@v2
        with:
          name: jupyter_core dist ${{ github.run_number }}
          path: ./dist

  test:
    needs: [build]
    runs-on: ${{ matrix.os }}-latest
    strategy:
      matrix:
        os: [ubuntu, macos, windows]
        python-version: [3.6, 3.7, 3.8, 3.9, pypy3]
        include:
          - os: ubuntu
            py-cmd: python
          - os: macos
            py-cmd: python3
          - os: windows
            py-cmd: python
          # different dists
          - python-version: 3.6
            dist: 'jupyter-core*.tar.gz'
          - python-version: 3.7
            dist: 'jupyter_core*.whl'
          - python-version: 3.8
            dist: 'jupyter-core*.tar.gz'
          - python-version: 3.9
            dist: 'jupyter_core*.whl'
          - python-version: pypy3
            dist: 'jupyter-core*.tar.gz'
        exclude:
          - os: windows
            python-version: pypy3
    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v2
        with:
          name: jupyter_core dist ${{ github.run_number }}
          path: ./dist

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Upgrade packaging deps
        run: |
          ${{ matrix.py-cmd }} -m pip install --upgrade pip wheel setuptools

      - name: Install distribution and test dependencies
        run: |
          set -eux
          ${{ matrix.py-cmd }} -m pip install -vv $(${{ matrix.dist }}) -r dev-requirements.txt codecov
          ${{ matrix.py-cmd }} -m pip check

      - name: Test with pytest
        run: |
          set -eux
          ${{ matrix.py-cmd }} -m pytest -vv --ff --pyargs=jupyter_core --cov=jupyter_core --cov-report=term-missing:skip-covered --cov-report=html --no-cov-on-fail

      - name: Upload coverage
        if: ${{ matrix.python-version != 'pypy3' }}
        run: |
          set -eux
          ${{ matrix.py-cmd }} -m codecov

      - name: Test setuptools example
        run: |
          set -eux
          cd examples/jupyter_path_entrypoint_setuptools
          ${{ matrix.py-cmd }} -m pip install -e .
          ${{ matrix.py-cmd }} -m jupyter --paths | tee paths.txt
          cat paths.txt | grep jupyter_path_entrypoint_setuptools/share/jupyter
          cat paths.txt | grep jupyter_path_entrypoint_setuptools/etc/jupyter

      - name: Test flit example
        run: |
          set -eux
          ${{ matrix.py-cmd }} -m pip install flit
          cd examples/jupyter_path_entrypoint_flit
          ${{ matrix.py-cmd }} -m pip install -e .
          ${{ matrix.py-cmd }} -m jupyter --paths | tee paths.txt
          cat paths.txt | grep jupyter_path_entrypoint_flit/share/jupyter
          cat paths.txt | grep jupyter_path_entrypoint_flit/etc/jupyter
